# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'LzWeather' do

  # Pods for LzWeather

pod 'Alamofire', '~> 4.7.2'
pod 'SwiftyJSON', '~> 4.1.0'
pod 'HandyJSON', '~> 4.2.1'
pod 'AMapLocation-NO-IDFA', '~> 2.6.2'
pod 'SnapKit', '~> 4.2.0'


end
